spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/inventorymgmtdb
    username: postgres
    password: welcome1
  jpa:
    generate-ddl: false
    show-sql: true
    database: org.hibernate.dialect.PostgreSQLDialect
stock:
  transportType: air
  slaDays: 2
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka
